"""Phase 34C -- Multimodal Qdrant indexer.

Idempotent upsert / delete of image knowledge points in the existing
Qdrant collection (``settings.QDRANT_COLLECTION``).

Design contract:

* A single Qdrant point represents ONE image. The point id is the
  deterministic hash of ``(document_id, image_id, schema_version)``
  produced by ``knowledge_record.compute_point_id``. Repeated
  indexing of the same image hits the same point id and overwrites
  the payload in place -- no duplicates.
* The embedding is generated by the existing text embedding
  provider (``app.services.embeddings.get_embedding_provider``); no
  new provider is introduced.
* The payload schema is documented in the Phase 34C plan:
  ``source_type=image_knowledge``, ``document_id``, ``image_id``,
  ``owner_user_id``, ``visibility``, ``source_file_name``,
  ``mime_type``, ``image_type``, ``vision_provider``, ``vision_model``,
  ``is_ocr``, ``has_vision``, ``knowledge_schema_version``,
  ``content``, ``title``, plus embedding metadata.
* No secrets / raw image bytes are ever written to Qdrant.
* Errors from the embedding provider or Qdrant are returned in the
  ``IndexResult`` -- the caller decides whether to retry, log, or
  escalate. The indexer itself never raises on a transient
  embedding / network failure.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from app.services.multimodal.config import MULTIMODAL_SOURCE_TYPE
from app.services.multimodal.knowledge_record import (
    ImageKnowledgeRecord,
    compute_point_id,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------


@dataclass
class IndexResult:
    """Outcome of a single ``upsert_image_knowledge`` call."""

    status: str = "skipped"          # upserted | skipped | disabled | error
    point_id: Optional[int] = None
    error: Optional[str] = None
    payload_size: int = 0
    knowledge_text_hash: Optional[str] = None
    embedding_dimension: Optional[int] = None
    embedding_model: Optional[str] = None
    is_ocr_only: bool = True

    def to_dict(self) -> Dict[str, Any]:
        return {
            "status": self.status,
            "point_id": self.point_id,
            "error": self.error,
            "payload_size": self.payload_size,
            "knowledge_text_hash": self.knowledge_text_hash,
            "embedding_dimension": self.embedding_dimension,
            "embedding_model": self.embedding_model,
            "is_ocr_only": self.is_ocr_only,
        }


@dataclass
class DeleteResult:
    """Outcome of a single ``delete_image_knowledge*`` call."""

    deleted: int = 0
    error: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {"deleted": self.deleted, "error": self.error}


# ---------------------------------------------------------------------------
# Settings helpers (lazy)
# ---------------------------------------------------------------------------


def _settings():
    from app.core.config import settings

    return settings


def _is_enabled() -> bool:
    try:
        return bool(_settings().MULTIMODAL_KNOWLEDGE_ENABLED)
    except Exception:
        return False


def _collection_name() -> str:
    return str(_settings().QDRANT_COLLECTION)


# ---------------------------------------------------------------------------
# Payload builder
# ---------------------------------------------------------------------------


def _build_payload(record: ImageKnowledgeRecord, *, embedding_model: str, embedding_dim: int) -> Dict[str, Any]:
    """Build the Qdrant payload for an image knowledge point.

    Stripped of ``None`` values so payloads stay tidy (mirrors the
    pattern used by ``app/services/vector/qdrant_service.py``).
    """
    payload: Dict[str, Any] = {
        # Routing / source type
        "source_type": MULTIMODAL_SOURCE_TYPE,
        "content_type": MULTIMODAL_SOURCE_TYPE,
        # Citation / RBAC anchors
        "document_id": int(record.document_id),
        "image_id": int(record.image_id),
        "owner_user_id": record.owner_user_id,
        "visibility": record.visibility or "global",
        "source_file_name": record.original_filename or "",
        # Human-readable label used by the citation renderer
        "title": record.original_filename or "",
        # Image / provenance metadata
        "mime_type": record.mime_type,
        "image_type": record.image_type or "unknown",
        "is_ocr": True,                       # OCR is always present (Phase 34C precondition)
        "has_vision": not record.is_ocr_only,
        # Knowledge text (used as the embedding source and for retrieval-side heuristics)
        "content": record.knowledge_text or "",
        "knowledge_text": record.knowledge_text or "",
        "knowledge_schema_version": int(record.knowledge_schema_version),
        # Vision provenance (empty strings when OCR-only)
        "vision_provider": record.vision_provider or "",
        "vision_model": record.vision_model or "",
        "vision_processed_at": record.vision_processed_at,
        # OCR provenance
        "ocr_status": record.ocr_status or "",
        "ocr_confidence": record.ocr_confidence,
        # Embedding metadata (for ops debugging; no secrets)
        "embedding_model": embedding_model,
        "embedding_dimension": int(embedding_dim),
    }
    # Optional: keep version_id if present, helps with reindex cycles
    if record.document_version_id is not None:
        payload["document_version_id"] = int(record.document_version_id)
    # Strip None values
    return {k: v for k, v in payload.items() if v is not None}


# ---------------------------------------------------------------------------
# Upsert
# ---------------------------------------------------------------------------


def upsert_image_knowledge(record: ImageKnowledgeRecord) -> IndexResult:
    """Upsert a single image knowledge point into Qdrant.

    Idempotent: the same ``(document_id, image_id, schema_version)``
    tuple always resolves to the same point id, so repeated calls
    overwrite in place.

    Returns an ``IndexResult`` describing the outcome. Never raises on
    a transient provider error -- it returns ``status="error"`` with
    a short ``error`` message instead.
    """
    if not _is_enabled():
        return IndexResult(status="disabled", error="multimodal_disabled")

    if record is None:
        return IndexResult(status="skipped", error="null_record")
    if not record.knowledge_text:
        return IndexResult(status="skipped", error="empty_knowledge_text")

    # Lazy imports so test environments that mock the embedding
    # provider can patch them before this function runs.
    try:
        from app.services.embeddings import get_embedding_provider
    except Exception as exc:
        return IndexResult(status="error", error=f"embedding_import_failed: {exc}")

    try:
        provider = get_embedding_provider()
        embedding = provider.embed([record.embedding_text or record.knowledge_text])[0]
        embedding_model = str(getattr(provider, "model_name", "unknown"))
        embedding_dim = int(getattr(provider, "dimension", len(embedding)))
    except Exception as exc:
        logger.warning(
            "multimodal: embedding failed for image_id=%s: %s",
            getattr(record, "image_id", None), exc,
        )
        return IndexResult(status="error", error=f"embedding_failed: {str(exc)[:160]}")

    try:
        from qdrant_client.models import PointStruct
        from app.services.vector.qdrant_service import get_qdrant_client
    except Exception as exc:
        return IndexResult(status="error", error=f"qdrant_import_failed: {exc}")

    point_id = compute_point_id(
        record.document_id,
        record.image_id,
        record.knowledge_schema_version,
    )
    payload = _build_payload(
        record,
        embedding_model=embedding_model,
        embedding_dim=embedding_dim,
    )

    try:
        client = get_qdrant_client()
        client.upsert(
            collection_name=_collection_name(),
            points=[PointStruct(id=point_id, vector=embedding, payload=payload)],
        )
    except Exception as exc:
        logger.warning(
            "multimodal: Qdrant upsert failed for image_id=%s point_id=%s: %s",
            record.image_id, point_id, exc,
        )
        return IndexResult(
            status="error",
            point_id=point_id,
            error=f"qdrant_upsert_failed: {str(exc)[:160]}",
        )

    return IndexResult(
        status="upserted",
        point_id=point_id,
        payload_size=len(payload),
        knowledge_text_hash=_text_hash(record.knowledge_text),
        embedding_dimension=embedding_dim,
        embedding_model=embedding_model,
        is_ocr_only=record.is_ocr_only,
    )


def _text_hash(text: str) -> Optional[str]:
    try:
        import hashlib

        return hashlib.sha256((text or "").encode("utf-8")).hexdigest()[:16]
    except Exception:
        return None


# ---------------------------------------------------------------------------
# Delete helpers
# ---------------------------------------------------------------------------


def _build_image_filter(image_id: int):
    """Qdrant filter for image knowledge points of a single image."""
    from qdrant_client.models import Filter, FieldCondition, MatchValue

    return Filter(must=[
        FieldCondition(key="image_id", match=MatchValue(value=int(image_id))),
        FieldCondition(key="source_type", match=MatchValue(value=MULTIMODAL_SOURCE_TYPE)),
    ])


def _build_document_filter(document_id: int):
    from qdrant_client.models import Filter, FieldCondition, MatchValue

    return Filter(must=[
        FieldCondition(key="document_id", match=MatchValue(value=int(document_id))),
        FieldCondition(key="source_type", match=MatchValue(value=MULTIMODAL_SOURCE_TYPE)),
    ])


def _delete_with_filter(scroll_filter, *, collection: Optional[str] = None) -> DeleteResult:
    """Generic Qdrant scroll + delete by filter."""
    if not _is_enabled():
        return DeleteResult(deleted=0)
    try:
        from app.services.vector.qdrant_service import get_qdrant_client
    except Exception as exc:
        return DeleteResult(error=f"qdrant_import_failed: {exc}")
    try:
        client = get_qdrant_client()
        results = client.scroll(
            collection_name=collection or _collection_name(),
            scroll_filter=scroll_filter,
            limit=1000,
            with_payload=False,
            with_vectors=False,
        )
        points = results[0] if results else []
        ids = [p.id for p in points]
        if ids:
            client.delete(collection_name=collection or _collection_name(), points=ids)
        return DeleteResult(deleted=len(ids))
    except Exception as exc:
        logger.warning("multimodal: delete failed: %s", exc)
        return DeleteResult(error=f"qdrant_delete_failed: {str(exc)[:160]}")


def delete_image_knowledge(image_id: int) -> DeleteResult:
    """Remove image knowledge points for a single ``DocumentImage.id``.

    Returns the number of points deleted (0 if none existed). Safe to
    call multiple times -- missing points simply produce 0.
    """
    if not image_id:
        return DeleteResult(deleted=0, error="invalid_image_id")
    return _delete_with_filter(_build_image_filter(int(image_id)))


def delete_image_knowledge_by_document_id(document_id: int) -> DeleteResult:
    """Remove image knowledge points for a single ``Document.id``.

    This is called alongside ``qdrant_service.delete_vectors_by_document_id``
    so the Phase 34C points are guaranteed cleared even if a future
    change splits point storage by source_type.
    """
    if not document_id:
        return DeleteResult(deleted=0, error="invalid_document_id")
    return _delete_with_filter(_build_document_filter(int(document_id)))


def delete_image_knowledge_by_image_ids(image_ids: List[int]) -> DeleteResult:
    """Batch variant used by reindex. Accepts a list of image_ids."""
    if not image_ids:
        return DeleteResult(deleted=0)
    # Qdrant supports multi-value 'should' OR filter; do them in
    # small batches to keep scroll responses bounded.
    total = 0
    last_error: Optional[str] = None
    for image_id in image_ids:
        r = delete_image_knowledge(int(image_id))
        total += r.deleted
        if r.error:
            last_error = r.error
    return DeleteResult(deleted=total, error=last_error)


# ---------------------------------------------------------------------------
# Convenience: fetch a point by its deterministic id
# ---------------------------------------------------------------------------


def fetch_image_knowledge_point(document_id: int, image_id: int, schema_version: int = 1) -> Optional[Dict[str, Any]]:
    """Return the payload of an image knowledge point, or ``None``."""
    if not _is_enabled():
        return None
    point_id = compute_point_id(int(document_id), int(image_id), int(schema_version))
    try:
        from app.services.vector.qdrant_service import get_qdrant_client

        client = get_qdrant_client()
        pts = client.retrieve(
            collection_name=_collection_name(),
            ids=[point_id],
            with_payload=True,
            with_vectors=False,
        )
    except Exception:
        return None
    if not pts:
        return None
    return getattr(pts[0], "payload", None) or None


__all__ = [
    "IndexResult",
    "DeleteResult",
    "upsert_image_knowledge",
    "delete_image_knowledge",
    "delete_image_knowledge_by_document_id",
    "delete_image_knowledge_by_image_ids",
    "fetch_image_knowledge_point",
    "MULTIMODAL_SOURCE_TYPE",
]
